default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: piyush-mishra-00
  password: root
  pool: 5

development:
  <<: *default
  database: my_clinic_app_development

test:
  <<: *default
  database: my_clinic_app_test

production:
  <<: *default
  database: my_clinic_app_production
  username: my_clinic_app
  password: <%= ENV['MY_CLINIC_APP_DATABASE_PASSWORD'] %>
